### ISSUE TITLE
Migrating component styling to Sass-based

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1733]
## Summary

styled-components로 스타일링된 컴포넌트의 스타일링을 Sass 기반의 스타일링으로 변경합니다.

## Description

Box, Text 컴포넌트를 참고해주세요.

- `as` 속성은 직접 구현합니다.
  - Breaking change: 컴포넌트별`as` 속성이 꼭 필요한지 체크하고, 불필요하다면 제거. 왠만한 컴포넌트에는 불필요할 것으로 예상합니다.
- 동적 스타일(e.g. width)은 style, 그 외 정적 스타일(e.g. size, variant)은 nested class를 통해 구현합니다.
- 스타일을 `@layer components` 로 감싸줘야합니다.

### 유의사항

1. `interpolation` 속성은 제거해주세요. CSS-in-JS 를 사용하지 않으므로 사용할 수 없는 속성입니다. `style` 속성을 통해 외부에서 인라인 스타일로 주입하는 방식으로 변경합니다. 마찬가지로 `***Interpolation` 속성은 `***Style` 속성으로 변경합니다.
2. number enum은 string 기반으로 변경합니다(e.g. `S: 20` -> `S: 's'`)

```[tasklist]
### Components
- [x] AlphaCenter(Center) @sungik-choi
- [x] AlphaSmoothCornersBox @sungik-choi
- [x] AlphaStack @sungik-choi
- [x] Avatar @yangwooseong
- [x] Banner @sungik-choi
- [x] Button @sungik-choi
- [x] ButtonGroup @sungik-choi
- [x] Divider @yangwooseong
- [x] Emoji @yangwooseong
- [x] Checkbox @sungik-choi
- [x] FormControl @yangwooseong
- [x] FormGroup @yangwooseong
- [x] FormHelperText @yangwooseong
- [x] FormLabel @yangwooseong
- [x] RadioGroup @sungik-choi
- [x] SegmentedControl @sungik-choi
- [x] Slider @yangwooseong
- [x] Switch @yangwooseong
- [x] Help @yangwooseong
- [x] Icon @yangwooseong
- [x] ~~LegacySegmentedControl~~ (이미 없어진 컴포넌트)
- [x] ListMenuTitle @yangwooseong
- [x] ConfirmModal @sungik-choi
- [x] Modal @sungik-choi
- [x] NavGroup @yangwooseong
- [x] NavItem @yangwooseong
- [x] Spinner @sungik-choi
- [x] Stack(LegacyStack) @sungik-choi
- [x] Status @yangwooseong
- [x] Tabs @sungik-choi
- [x] Tag @yangwooseong
- [x] Badge @yangwooseong
- [x] Text @yangwooseong
- [x] Toast @sungik-choi
- [x] Tooltip @yangwooseong
- [x] CheckableAvatar @sungik-choi
```

```[tasklist]
### Components (Composition)
- [x] AvatarGroup @yangwooseong
- [x] Select @sungik-choi
- [x] TextArea @sungik-choi
- [x] TextField @sungik-choi
- [x] KeyValueListItem @sungik-choi
- [x] ~~LegacyRadio~~ @sungik-choi
- [x] LegacyTooltip @sungik-choi
- [x] ListItem @sungik-choi
- [x] OutlineItem @sungik-choi
- [x] Overlay @sungik-choi
- [x] ProgressBar @sungik-choi
- [x] SectionLabel @sungik-choi
```

### References

- #1106
