### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1800]
```[tasklist]
### v2.0.0
- [ ] #1106
- [ ] https://github.com/channel-io/bezier-react/issues/1733
- [ ] #994
- [ ] #690
- [ ] #1690
- [ ] #740
- [ ] https://github.com/channel-io/bezier-react/issues/1732
- [ ] Remove `interpolation` interface
- [ ] Change `***Interpolation` to inline style prop
- [ ] Remove some deprecated components
- [ ] #1780
- [ ] #1792 
- [ ] #1793 
- [ ] #1794 
- [ ] #1798 
```
