### ISSUE TITLE
Responding to new repository for static icon asset

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2229]
## Summary

- 채널 팀의 내부 사정에 따라 정적으로 아이콘을 가지고 있는 레포지토리(가칭: `beizer-asset`)를 생성하고, `bezier-icons` 에서 이 레포지토리에 있는 svg를 활용할 예정입니다. 그에 따라서 `bezier-icons`, `bezier-figma-plugin` 패키지의 역할이 변경되어야 하기 때문에 대응이 필요합니다. 예를 들면 현재는 `bezier-icons` 에서 빌드 타임에 svg 최적화를 진행하지만, 이제 `bezier-asset` 에 svg 최적화를 진행한 상태에서 에셋을 업로드 해야합니다. 이에 따라 `bezier-figma-plugin`에서 런타임에 svgo를 호출해야 합니다. 또한, `bezier-icons`에서 적용하고 있는 web specific한 최적화 옵션을 그대로 주는 것이 좋을 지 고민이 필요합니다.  

추가)

- bezier-figma-plugin 에서 svgo optimize 를 적용하면 require('os') 와 같은 모듈을 사용하지 못해서 에러가 뜨는 문제가 있음. plugin에서는 svg를 그대로 json으로 올려주고 GitHub action (`generating-icon-files.yml`)에서 optimize 하는 방향으로 테스트 완료

## Description

```[tasklist]
### Tasks
- [x] `bezier-figma-plugin`에서 icons.json 파일 업로드 대상이 되는 repo 변경 후 배포
- [x] `bezier-asset`에서 아이콘 에셋 만들 때 optimizing 적용
- [x] `bezier-icons`의 workflow 일부를 bezier-asset으로 이동
- [x] `bezier-asset`에서 아이콘 업데이트 PR이 머지되면 `bezier-react`에 연동 PR올리는 workflow 생성
```

### References

- None
