### ISSUE TITLE
Enhance `bezier-vscode` pacakge

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2485]
## Summary

- bezier-vscode 패키지를 개선합니다. 

## Description

- 현재는 `var(--bgtxt-black-dark)`를 입력하기 위해 `var`를 입력하고, `bg...`를 입력하면 자동완성 리스트가 뜹니다. `--`로는 VS Code가 자동완성 매칭을 해주고 있지 않아서 이렇게 개발했지만, 사용자 입장에서는 `var` 입력 후 `--` 가 아닌 `bg`를 입력해야 한다는 것이 다소 직관적이지 않습니다.  `bg` 만 입력해도 자동완성 리스트가 뜨고, 탭 키로 완성하면 `var(--bgtxt-black-dark)` 가 삽입되는 형태로 개선하면 좋겠습니다. 

https://github.com/user-attachments/assets/4498add0-820c-4154-9b72-cbf8234af468

- V2 토큰까지 자동완성을 지원합니다. 
- [위키](https://github.com/channel-io/bezier-react/wiki/Introduction)에 문서를 추가합니다. 
- 배포 프로세스를 깃헙 액션으로 자동화하면 좋겠습니다. https://github.com/channel-io/bezier-react/pull/2153#pullrequestreview-1993577792

```[tasklist]
### Tasks
- [x] 자동완성 로직 변경
- [x] V2 토큰 지원
- [x] 위키 문서 추가
- [x] 배포 프로세스 자동화
```

### References

- None
