### ISSUE TITLE
Umbrella Issue: styled-components

### ISSUE THREAD

**Issue by jwoo0122** [channel-io/bezier-react#457]
- [ ] babel-plugin-styled-components
  - [ ] Display name option https://styled-components.com/docs/tooling#better-debugging
  - [ ] Minification https://styled-components.com/docs/tooling#minification
  - [ ] Tree-shakable https://styled-components.com/docs/tooling#dead-code-elimination
- [ ] typescript-plugin-styled-components (@rollup/plugin-typescript 없으면 못 쓸 가능성 있음, transpile 고민할 것) https://github.com/Igorbek/typescript-plugin-styled-components#Integration-with-Rollup

**Comment by sungik-choi** [comment]
정확히 어떤 이슈인가요?

**Comment by quino0627** [comment]
일단 해결되긴 했죠..😅 
close comment 하겠습니다
