### ISSUE TITLE
Release pipeline umbrella issue

### ISSUE THREAD

**Issue by jwoo0122** [channel-io/bezier-react#478]
- [ ] Default branch (master -> exp)
issue close 를 PR description 으로 automatic 하게 관리하려면, PR 의 base branch 를 github default branch 로 변경해야 함. 혹은 master branch commit message (exp -> master) 를 더 정확하게 작성할 필요가 있음.
- [ ] SemanticRelease https://github.com/semantic-release/semantic-release
PR name 의 prefix 를 이용해 버전 관리를 자동으로 할 수 있도록 구성 필요.
- [ ] semver 자동화를 위한 commit 메세지 자동생성 cli https://github.com/commitizen/cz-cli
