### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#983]
### Description

파운데이션, 컴포넌트에 대한 문서(mdx, JSDoc)을 작성해야합니다.

### Reasons for suggestion

라이브러리 사용자와 메인테이너(채널 멤버)에게 파운데이션, 컴포넌트의 올바른 사용법을 알려주기 위해서 문서화를 진행합니다.

### Proposed solution

- 문서를 작성하고자하는 메인테이너는 먼저 이슈(e.g. #988)를 생성해주세요.
- 해당 모듈을 구현한 엔지니어가 문서도 함께 작성해주시길 기대합니다.
- 컴포넌트를 재구현하는 경우, 문서화를 함께 진행합니다.

```[tasklist]
### Components
- [x] #880 
- [x] #808 
- [x] #811
- [x] #984
- [ ] #985
- [ ] #986
- [ ] #987
- [ ] #988 
- [ ] #980 
- [ ] #990
- [ ] #991
- [x] #709 
- [ ] #992
- [ ] Write documentation for `Slider` component
- [ ] Write documentation for `Switch` component
- [x] #711 
- [ ] #1060
- [ ] Write documentation for `Help` component
- [x] #905 
- [ ] Write documentation for `KeyValueListItem` component
- [ ] Write documentation for `ListItem` component
- [ ] Write documentation for `ListMenuTitle` component
- [x] #978 
- [ ] Write documentation for `NavGroup` component
- [ ] Write documentation for `NavItem` component
- [ ] Write documentation for `OutlineItem` component
- [ ] Write documentation for `Overlay` component
- [x] #1034
- [ ] Write documentation for `SectionLabel` component
- [ ] Write documentation for `Spinner` component
- [x] #807 
- [ ] Write documentation for `Status` component
- [ ] Write documentation for `Tabs` component
- [x] #982 
- [ ] #1072 
- [x] #925 
- [ ] Write documentation for `Text` component
- [ ] Write documentation for `Toast` component
- [x] #979 
```

### Foundation

> Foundation의 경우, `beizer-react` 내부의 구현이 바꿀 여지가 있습니다.

### References

- #931 
- [PRs](https://github.com/channel-io/bezier-react/pulls?q=is%3Apr+label%3Adocumentation+is%3Aclosed)

**Comment by sungik-choi** [comment]
디자인 시스템 리빌드가 진행중이므로, 스펙 변경 여지가 있어 잠시 펜딩합니다.

**Comment by sungik-choi** [comment]
디자인 시스템 리빌드(v2)로 컴포넌트 변경이 많습니다. 기존 버전의 컴포넌트(v1)의 문서화는 큰 의미가 없다고 판단하여 관련 이슈는 Close합니다.
