### ISSUE TITLE
Create bezier-icon package

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#993]
### Description

아이콘 소스를 별도의 패키지(`bezier-icons` - 미정)로 분리합니다.

### Reasons for suggestion

- 아이콘 소스의 업데이트는 `bezier-react` 의 다른 컴포넌트와 별도로 이루어지는 편이 좋습니다. 즉, 별도로 버전 관리가 되어야합니다.
  - 새롭게 아이콘셋이 업데이트 되었을 때, 그리고 해당 아이콘셋이 프로덕션에 빠르게 적용되어야 하는 상황에서 `bezier-react` 의 다른 Breaking Change가 릴리즈 대기중이라면 곤란한 상황이 발생합니다.
- 아이콘 소스는 **React 라는 웹 프레임워크를 벗어나서 플랫폼 공통으로 사용할 수 있습니다**. `svg` 뿐만 아니라, `png` 등의 포맷도 피그마 플러그인과 연동하여 자동화한다면 팀 전체의 생산성을 향상시킬 수 있습니다.

### Proposed solution

- svg asset, React Component(`IconSource`)만을 별도로 관리하는 패키지를 생성합니다.
- 빌드에 문제가 없는지 검토합니다.
  - 빌드는 잘 되는지? 런타임 에러는 발생하지 않는지?
  - 트리 쉐이킹은 잘 되는지?
  - 번들 사이즈의 변화가 있는지?
- 마이그레이션을 진행합니다.

### References

- https://github.com/Shopify/polaris/tree/main/polaris-icons

**Comment by sungik-choi** [comment]
- [ ] svg optimize, `fill=currentColor` transform
- [ ] storybook merge
- [ ] bezier-react migration
- [ ] ch-* app migration
